#!/bin/sh

##
## This script calculates how much disk space is used by each file type (e.g. "txt", "fq")
##

find -type f -printf "%f\t%s\n" |
	perl -npe 's/.*\.([^\.]+)\t/\1\t/'  |
	sort -k1V,1 |
	groupBy -g 1 -o sum -c 2 |
	sort -k2nr,2 |
	human.py --div 1000 --col 2 |
	sed 's/  */\t/g'
