#!/bin/sh

set -o pipefail

##
## Given a wild-card of file names (e.g. "*.fq"),
## prints the total size of the files, in human form (e.g. 6.5Gi)
##
GLOB="$1"
if [ -z "$GLOB" ]; then
	echo "
Print total size of given files.

Usage:
 $(basename $0) \"*.fq\"

Will print the sum of all fiels matching \"*.fq\", in human-friendly form (e.g. 6.5Gi).

NOTE:
1. If the parameter contains shell wild-cards, it must be quoted.
2. Only a single wild-card/filename can be specified.
3. Files are searched for using 'find', and sub-directories are also searched.

" >&1
	exit 1
fi

find -iname "$GLOB" -printf "%s\n" | awk '{sum+=$1}END{print sum}' | human.py --div 1000

