#!/bin/sh

# @autogenerated_warning@
# @autogenerated_timestamp@
# @PACKAGE@ @VERSION@
# @PACKAGE_URL@

COPYRIGHT="
Copyright (C) 2012-2014 A. Gordon (assafgordon@gmail.com)
License: GPLv3+
"

##
## Helper script to automatically view a tabular file
## with properly tabulated fields.
## See "detect_tab_stops --help" for details.
##

# executed without input filenames/redirection - show help
usage()
{
	BASE=$(basename $0)
	echo "
list-columns - list the field/column names in a given file, based on the first line.
Version: @VERSION@
$COPYRIGHT
See: @PACKAGE_URL@

Usage examples:
 $BASE [INPUT-FILE]
 $BASE < [INPUT-FILE]
 cat [INPUT-FILE] | $BASE

"
	exit
}

test "x$1" = "x-h" || test "x$1" = "x--help" && usage

awk -v FS="\t" '
{
	for (i=1;i<=NF;i++) {
		print i, $i
	}
	exit
}' "$@"
