#!/bin/sh

# @autogenerated_warning@
# @autogenerated_timestamp@
# @PACKAGE@ @VERSION@
# @PACKAGE_URL@

COPYRIGHT="
Copyright (C) 2012-2014 A. Gordon (assafgordon@gmail.com)
License: GPLv3+
"

##
## Helper script to automatically view a tabular file
## with properly tabulated fields.
## See "detect_tab_stops --help" for details.
##

usage()
{
	BASE=$(basename $0)
	echo "
nfs_iostat - Friendly monitoring of NFS I/O statistics
Version: @VERSION@
$COPYRIGHT
See: @PACKAGE_URL@

Usage:
  $BASE

Will print NFS I/O statistics every 1 second.

"
    exit
}

test "x$1" = "x-h" || test "x$1" = "x--help" && usage

## Prints NFS activelty (iostat -n),
## with pretty formatting (accomodating long-named NFS mounts)
##
iostat -n 1 \
    | stdbuf -o L sed 's/  */\t/g' \
    | expand -t 40,54,65,76,87,98,109,120,131

