#!/bin/sh

# @autogenerated_warning@
# @autogenerated_timestamp@
# @PACKAGE@ @VERSION@
# @PACKAGE_URL@

COPYRIGHT="
Copyright (C) 2012-2014 A. Gordon (assafgordon@gmail.com)
License: GPLv3+
"

##
## Prints the total size used by file types
##

die()
{
    BASE=$(basename -- "$0")
    echo "$BASE: error: $@" >&2
    exit 1
}

usage()
{
	BASE=$(basename $0)
	echo "
sum_file_sizes - Prints the total size of all specified files
Version: @VERSION@
$COPYRIGHT
See: @PACKAGE_URL@

Usage:
 $BASE \"*.txt\"

Will print the sum of all files matching \"*.txt\" (in the current directory),
in human-friendly form (e.g. 6.5Gi).

NOTE:
1. If the parameter contains shell wild-cards, it must be quoted.
2. Only a single wild-card/filename can be specified.
3. Files are searched for using 'find', and sub-directories are also searched.

"
	exit 0
}

test "x$1" = "x-h" || test "x$1" = "x--help" && usage
test -z "$1" && die "missing file glob (e.g. '*.txt'). See --help for details."

GLOB=$1

find -iname "$GLOB" -printf "%s\n" \
    | awk '{sum+=$1}END{print sum}' \
    | human.py --div 1000 \
    | sed 's/ //g'
